"""init

Revision ID: 3b1b89956e5f
Revises: cdf95f94c11c
Create Date: 2025-08-09 14:02:43.849606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1b89956e5f'
down_revision: Union[str, Sequence[str], None] = 'cdf95f94c11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fattura', sa.Column('inviata_sns', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fattura', 'inviata_sns')
    # ### end Alembic commands ###
