"""init

Revision ID: 47398487e85c
Revises: 
Create Date: 2025-08-08 19:52:15.900033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47398487e85c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=False),
    sa.Column('indirizzo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale')
    )
    op.create_table('fattura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('progressivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('importo_prestazione', sa.Float(), nullable=False),
    sa.Column('bollo', sa.Boolean(), nullable=True),
    sa.Column('descrizione', sa.String(length=255), nullable=False),
    sa.Column('totale', sa.Float(), nullable=False),
    sa.Column('numero_sedute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fattura')
    op.drop_table('cliente')
    # ### end Alembic commands ###
