"""init

Revision ID: 7b15069d642b
Revises: 47398487e85c
Create Date: 2025-08-08 20:11:44.372883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b15069d642b'
down_revision: Union[str, Sequence[str], None] = '47398487e85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fattura_progressivo',
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('last_progressivo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('anno')
    )
    op.add_column('fattura', sa.Column('data_fattura', sa.Date(), nullable=False))
    op.add_column('fattura', sa.Column('data_pagamento', sa.Date(), nullable=True))
    op.add_column('fattura', sa.Column('metodo_pagamento', sa.String(length=50), nullable=True))
    op.drop_column('fattura', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fattura', sa.Column('data', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('fattura', 'metodo_pagamento')
    op.drop_column('fattura', 'data_pagamento')
    op.drop_column('fattura', 'data_fattura')
    op.drop_table('fattura_progressivo')
    # ### end Alembic commands ###
