"""Costi

Revision ID: 9b045b910089
Revises: 3b1b89956e5f
Create Date: 2025-08-12 00:47:09.396409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b045b910089'
down_revision: Union[str, Sequence[str], None] = '3b1b89956e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=False),
    sa.Column('anno_riferimento', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('totale', sa.Float(), nullable=False),
    sa.Column('pagato', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('costo')
    # ### end Alembic commands ###
