"""init

Revision ID: cdf95f94c11c
Revises: 7b15069d642b
Create Date: 2025-08-08 21:10:32.937012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf95f94c11c'
down_revision: Union[str, Sequence[str], None] = '7b15069d642b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('citta', sa.String(length=255), nullable=True))
    op.add_column('cliente', sa.Column('cap', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'cap')
    op.drop_column('cliente', 'citta')
    # ### end Alembic commands ###
